// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2P9_EGhnj0SjqU2ObxgiZwpylWbT6z9A',
    appId: '1:556596486577:web:153d867e6ae7d304581d90',
    messagingSenderId: '556596486577',
    projectId: 'psgleadersbook',
    authDomain: 'psgleadersbook.firebaseapp.com',
    databaseURL: 'https://psgleadersbook-default-rtdb.firebaseio.com',
    storageBucket: 'psgleadersbook.firebasestorage.app',
    measurementId: 'G-E2X2EM21D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KG4Mr76FyCUOU_c9X1d_bi7Q4qBuMS0',
    appId: '1:556596486577:android:4f2020993f65a228581d90',
    messagingSenderId: '556596486577',
    projectId: 'psgleadersbook',
    databaseURL: 'https://psgleadersbook-default-rtdb.firebaseio.com',
    storageBucket: 'psgleadersbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpIRVWVOFCQEtqqn798dB1FUSWO16cJ4',
    appId: '1:556596486577:ios:5cf5295273800015581d90',
    messagingSenderId: '556596486577',
    projectId: 'psgleadersbook',
    databaseURL: 'https://psgleadersbook-default-rtdb.firebaseio.com',
    storageBucket: 'psgleadersbook.firebasestorage.app',
    androidClientId: '556596486577-dib9h84fh314u19onqbjkb1gdlt4o623.apps.googleusercontent.com',
    iosClientId: '556596486577-b7o6ekl9t4r8a0i3lafe60lcniapqsq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.psgLeadersBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPpIRVWVOFCQEtqqn798dB1FUSWO16cJ4',
    appId: '1:556596486577:ios:5cf5295273800015581d90',
    messagingSenderId: '556596486577',
    projectId: 'psgleadersbook',
    databaseURL: 'https://psgleadersbook-default-rtdb.firebaseio.com',
    storageBucket: 'psgleadersbook.firebasestorage.app',
    androidClientId: '556596486577-dib9h84fh314u19onqbjkb1gdlt4o623.apps.googleusercontent.com',
    iosClientId: '556596486577-b7o6ekl9t4r8a0i3lafe60lcniapqsq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.psgLeadersBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2P9_EGhnj0SjqU2ObxgiZwpylWbT6z9A',
    appId: '1:556596486577:web:ad2db5844a2014b7581d90',
    messagingSenderId: '556596486577',
    projectId: 'psgleadersbook',
    authDomain: 'psgleadersbook.firebaseapp.com',
    databaseURL: 'https://psgleadersbook-default-rtdb.firebaseio.com',
    storageBucket: 'psgleadersbook.firebasestorage.app',
    measurementId: 'G-H23LNXK89Z',
  );
}
